### DISCUSSION TITLE
How to set log level to WARN

### DISCUSSION THREAD

**Discussion by mavogel** [k8ssandra/management-api-for-apache-cassandra#643] [Q&A]
Hi,
I was wondering how to set the log level to WARN? I am using the image `k8ssandra/cass-management-api:5.0.3-ubi8`

Here is what I tried:
```yaml
containers:
  # other props
   - name: cassandra
     image: k8ssandra/cass-management-api:5.0.3-ubi8
     env:
        - name: LOG_LEVEL
          value: WARN
        - name: MGMT_API_JAVA_OPTS
          value: -Dlogback.rootLogger.level=WARN
```

However I still get log messages such as
```console
cassandra INFO  [nioEventLoopGroup-2-2] 2025-05-15 11:00:47,274 Cli.java:672 - address=/10.xxx.xx.xx:51206 url=/api/v0/probes/readiness status=200 OK
```

Any help is appreciated :)
