### ISSUE TITLE
Additional metrics relabeling for the new endpoint

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/management-api-for-apache-cassandra#255]
Our service monitors in K8ssandra had some relabelling rules which are convenient when building dashboards and should probably be done out of the box in the new metrics endpoint.

Request type and consistency levels extraction:

```
        - regex: org\.apache\.cassandra\.metrics\.client_request\.(\w+)\.(\w+)$
          replacement: ${2}
          sourceLabels:
            - mcac
          targetLabel: request_type
        - regex: org\.apache\.cassandra\.metrics\.client_request\.(\w+)\.(\w+)$
          replacement: org_apache_cassandra_metrics_client_request_${1}
          sourceLabels:
            - mcac
          targetLabel: __name__
         - regex: org\.apache\.cassandra\.metrics\.client_request\.(\w+)\.(\w+)\.(\w+)$
          replacement: ${3}
          sourceLabels:
            - mcac
          targetLabel: cl
         - regex: >-
          org\.apache\.cassandra\.metrics\.client_request\.(\w+)\.(\w+)\.(\w+)$
          replacement: ${2}
          sourceLabels:
            - mcac
          targetLabel: request_type
        - regex: >-
            org\.apache\.cassandra\.metrics\.client_request\.(\w+)\.(\w+)\.(\w+)$
          replacement: org_apache_cassandra_metrics_client_request_${1}_cl
          sourceLabels:
            - mcac
          targetLabel: __name__
```

Thread pool type/name extraction:

```
        - regex: org\.apache\.cassandra\.metrics\.thread_pools\.(\w+)\.(\w+)\.(\w+).*
          replacement: ${2}
          sourceLabels:
            - mcac
          targetLabel: pool_type
        - regex: org\.apache\.cassandra\.metrics\.thread_pools\.(\w+)\.(\w+)\.(\w+).*
          replacement: ${3}
          sourceLabels:
            - mcac
          targetLabel: pool_name
        - regex: org\.apache\.cassandra\.metrics\.thread_pools\.(\w+)\.(\w+)\.(\w+).*
          replacement: org_apache_cassandra_metrics_thread_pools_${1}
          sourceLabels:
            - mcac
          targetLabel: __name__
```

Dropped message types extraction:

```
        - regex: org\.apache\.cassandra\.metrics\.dropped_message\.(\w+)\.(\w+)
          replacement: ${2}
          sourceLabels:
            - mcac
          targetLabel: message_type
        - regex: org\.apache\.cassandra\.metrics\.dropped_message\.(\w+)\.(\w+)
          replacement: org_apache_cassandra_metrics_dropped_message_${1}
          sourceLabels:
            - mcac
          targetLabel: __name__
```

Streaming peer IP extraction:

```
        - regex: org\.apache\.cassandra\.metrics\.streaming\.(\w+)\.(.+)$
          replacement: ${2}
          sourceLabels:
            - mcac
          targetLabel: peer_ip
        - regex: org\.apache\.cassandra\.metrics\.streaming\.(\w+)\.(.+)$
          replacement: org_apache_cassandra_metrics_streaming_${1}
          sourceLabels:
            - mcac
          targetLabel: __name__
        - regex: org\.apache\.cassandra\.metrics\.streaming\.(\w+)$
          replacement: org_apache_cassandra_metrics_streaming_${1}
          sourceLabels:
            - mcac
          targetLabel: __name__
```

Hinted handoff:

```
        - regex: >-
            org\.apache\.cassandra\.metrics\.hinted_hand_off_manager\.([^\-]+)-(\w+)
          replacement: ${2}
          sourceLabels:
            - mcac
          targetLabel: peer_ip
        - regex: >-
            org\.apache\.cassandra\.metrics\.hinted_hand_off_manager\.([^\-]+)-(\w+)
          replacement: org_apache_cassandra_metrics_hinted_hand_off_manager_${1}
          sourceLabels:
            - mcac
          targetLabel: __name__
        - regex: org\.apache\.cassandra\.metrics\.hints_service\.hints_delays\-(\w+)
          replacement: ${1}
          sourceLabels:
            - mcac
          targetLabel: peer_ip
        - regex: org\.apache\.cassandra\.metrics\.hints_service\.hints_delays\-(\w+)
          replacement: org_apache_cassandra_metrics_hints_service_hints_delays
          sourceLabels:
            - mcac
          targetLabel: __name__
```

Heap and GC related metrics:

```
        - regex: jvm\.gc\.(\w+)\.(\w+)
          replacement: ${1}
          sourceLabels:
            - mcac
          targetLabel: collector_type
        - regex: jvm\.gc\.(\w+)\.(\w+)
          replacement: jvm_gc_${2}
          sourceLabels:
            - mcac
          targetLabel: __name__
        - regex: jvm\.memory\.(\w+)\.(\w+)
          replacement: ${1}
          sourceLabels:
            - mcac
          targetLabel: memory_type
        - regex: jvm\.memory\.(\w+)\.(\w+)
          replacement: jvm_memory_${2}
          sourceLabels:
            - mcac
          targetLabel: __name__
        - regex: jvm\.memory\.pools\.(\w+)\.(\w+)
          replacement: ${2}
          sourceLabels:
            - mcac
          targetLabel: pool_name
        - regex: jvm\.memory\.pools\.(\w+)\.(\w+)
          replacement: jvm_memory_pools_${2}
          sourceLabels:
            - mcac
          targetLabel: __name__
```
