### ISSUE TITLE
How to filter metrics?

### ISSUE THREAD

**Issue by jpic** [k8ssandra/management-api-for-apache-cassandra#647]
Currently, many metrics are exported, a GET request on the metrics endpoint returns 100MB of data.

I've tried something like this:

```
 relabels:
  - regex: "org\\.apache\\.cassandra\\.metrics\\.streaming\\.(\\w+)\\.(.+)$" 
    sourceLabels: ["__origname__"]
    action: drop
```

But I'm having a null pointer exception

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/MAPI-124) by [Unito](https://www.unito.io)
┆Issue Number: MAPI-124
